In [1]:
#import the csv scraping 
import pandas as pd 

df = pd.read_csv(r"C:\Users\USER\Documents\PBA\SentimentAnalysis\planner_clean_reviews.csv")
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,review_length
0,6d130fcb-47b1-42fc-a032-bf97719ca5a4,Alexander Benkstein,https://play-lh.googleusercontent.com/a-/ALV-U...,principally good app pretty much unusable your...,2,0,1.18.36,2026-03-03 15:08:44,NaN,NaN,1.18.36,190
1,34f4642b-17ee-463b-ac28-05a902db1cb9,Thomas Watson,https://play-lh.googleusercontent.com/a/ACg8oc...,like far ill report later,3,0,1.18.36,2026-02-27 11:03:15,NaN,NaN,1.18.36,42
2,5a9342d9-8259-4c6f-b8b8-20b1096cf69d,Matt Winter,https://play-lh.googleusercontent.com/a-/ALV-U...,would load real assistance common days easier ...,1,1,1.18.36,2026-02-27 05:43:15,NaN,NaN,1.18.36,257
3,73a714db-ceb1-4b5d-a1af-64d953643ad9,Hugo Arista,https://play-lh.googleusercontent.com/a/ACg8oc...,experience app really good thing tools availab...,4,0,1.18.36,2026-02-24 23:49:27,NaN,NaN,1.18.36,252
4,79b2321f-1e26-4028-b553-da8b0d8896b4,Laura R,https://play-lh.googleusercontent.com/a-/ALV-U...,app complete failure planner used kanban board...,1,1,1.18.33,2026-02-17 05:10:32,NaN,NaN,1.18.33,490

In [2]:
#cleaning drop.na
df_clean = df.dropna(subset=["content",])
df_clean.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,review_length
0,6d130fcb-47b1-42fc-a032-bf97719ca5a4,Alexander Benkstein,https://play-lh.googleusercontent.com/a-/ALV-U...,principally good app pretty much unusable your...,2,0,1.18.36,2026-03-03 15:08:44,NaN,NaN,1.18.36,190
1,34f4642b-17ee-463b-ac28-05a902db1cb9,Thomas Watson,https://play-lh.googleusercontent.com/a/ACg8oc...,like far ill report later,3,0,1.18.36,2026-02-27 11:03:15,NaN,NaN,1.18.36,42
2,5a9342d9-8259-4c6f-b8b8-20b1096cf69d,Matt Winter,https://play-lh.googleusercontent.com/a-/ALV-U...,would load real assistance common days easier ...,1,1,1.18.36,2026-02-27 05:43:15,NaN,NaN,1.18.36,257
3,73a714db-ceb1-4b5d-a1af-64d953643ad9,Hugo Arista,https://play-lh.googleusercontent.com/a/ACg8oc...,experience app really good thing tools availab...,4,0,1.18.36,2026-02-24 23:49:27,NaN,NaN,1.18.36,252
4,79b2321f-1e26-4028-b553-da8b0d8896b4,Laura R,https://play-lh.googleusercontent.com/a-/ALV-U...,app complete failure planner used kanban board...,1,1,1.18.33,2026-02-17 05:10:32,NaN,NaN,1.18.33,490

In [4]:
df_clean_saved = df_clean.to_csv("planner_clean_na.csv", index=False)

In [ ]:
#Tokenization
from nltk.tokenize import word_tokenize

#output
# "I love this app"
# ↓
# ["I","love","this","app"]

In [ ]:
#Stemming
from nltk.stem import PorterStemmer

#output
# running
# runs
# runner
# ↓
# run

In [ ]:
#Regex Cleaning
import re

# output
# "app!!! very good :)"
# ↓
# "app very good"

In [ ]:
#Bag of words
from sklearn.feature_extraction.text import CountVectorizer

# output

In [ ]:
# N-Grams
from sklearn.feature_extraction.text import CountVectorizer

#output
# "app!!! very good :)"
# ↓
# "app very good"