In [3]:
#coisine similarities
import pandas as pd 
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.metrics.pairwise import cosine_similarity 
from bs4 import BeautifulSoup
import requests

In [1]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\user\miniconda3\lib\site-packages (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\user\miniconda3\lib\site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\user\miniconda3\lib\site-packages (from beautifulsoup4) (4.15.0)

In [4]:
data = "https://bnpb.go.id/berita/banjir-setinggi-1-5-meter-di-kota-ambon-kini-berangsur-surut"

In [92]:
def scrap_data(url): 
    contents = []
    try: 
        response = requests.get(url)
        if response.status_code == 404: 
            contents.append({"message": "can't access"})
        else : 
            soup = BeautifulSoup(response.content, 'html.parser')
            title = soup.find(class_="title").text
            paragraph = soup.find_all("p")
            content = "\n".join([p.text for p in paragraph])
            contents.append({"title":title, "content" : content })
            
    except Exception as e: 
        contents.append(str(e))
    return contents

In [93]:
result = scrap_data(data)
print(result)

[{'title': 'Banjir Setinggi 1,5 Meter di Kota Ambon, Kini Berangsur Surut', 'content': '\n\n                                    27 Jul 2022 23:48 WIB |\n                                     Dilihat 2347 kali \n                                \n\nFoto :  Kondisi rumah warga yang tergenang banjir di Kota Ambon, Provinsi Maluku, Selasa (26/7). (BPBD Kota Ambon)\n\nJAKARTA - Banjir yang melanda wilayah Kota Ambon, Provinsi Maluku pada Selasa (26/7) kini mulai berangsur surut. Kondisi curah hujan tinggi dan jebolnya tanggul bandara memicu banjir yang masuk hingga ke pemukiman warga. Hal ini juga mengakibatkan longsor di beberapa titik.\nBPBD Kota Ambon mencatat sebanyak enam unit rumah terdampak dan lima unit berpotensi longsor. Selain itu, terdapat 6 KK/24 jiwa terdampak di Desa Laha Kecamatan Teluk ambon dan Desa Hattu di Kecamatan Leihitu Barat.\nBanjir tersebut sempat membuat aktivitas para warga tersendat. Berdasarkan pantauan visual dilapangan, tinggi muka air sebelumnya terpantu hingga 1,5 meter. Para warga menggunakan tali untuk membantu berjalan kaki.\nPusat Pengendalian Operasi (Pusdalops) BNPB melaporkan berdasarkan informasi per Selasa (26/7) pukul 17.00 WIT kini akses jalan sudah bisa dilalui kendaraan truk. Upaya penanganan darurat juga terus dilakukan BPBD Kota Ambon dengan menjalin koordinasi antar lintas unit terkait pendataan dan distribusi permakanan bagi para warga terdampak.\nMerujuk informasi peringatan dini dari BMKG esok hari (28/7) untuk wilayah Ambon masih berpotensi hujan dengan intensitas ringan hingga sedang disertai petir. Menindaklanjuti informasi ini, BNPB mengimbau masyarakat dan perangkat daerah setempat untuk meningkatkan kewaspadaan dan kesiapsiagaan terhadap potensi bencana hidrometeorologi.\xa0\nMasyarakat dan perangkat daerah setempat dapat melakukan langkah-langkah kesiapsiagaan dengan membersihkan area aliran sungai dari beragam material yang menghambat aliran air, memantau peningkatan debit air ketika hujan berdurasi lama serta mengikuti instruksi otoritas daerah setempat dalam upaya tanggap darurat banjir.\n\nAbdul Muhari, Ph.D.\xa0\nPlt. Kepala Pusat Data, Informasi dan Komunikasi Kebencanaan BNPB\n  Nabilla/Shakira/Anggita/Apri \n  Apri Setiawan \nBanjir Kecamatan Bintan Timur Berangsur Surut\nPemkab Lanny Jaya Aktifkan Posko Tangani Bencana Kekeringan\nTelp.021-29827793\nFax.021-21281200 \nEmail: [email\xa0protected]\nTelp. +62 21 29827444 , 117 \n+62 812 1237 575 \nEmail:[email\xa0protected]'}]

In [94]:
df = pd.DataFrame(result)
df.head()

,title,content
0,"Banjir Setinggi 1,5 Meter di Kota Ambon, Kini ...",\n\n 27 Jul...

In [95]:
content = df["content"][0]
print(content)

                                    27 Jul 2022 23:48 WIB |
                                     Dilihat 2347 kali


Foto :  Kondisi rumah warga yang tergenang banjir di Kota Ambon, Provinsi Maluku, Selasa (26/7). (BPBD Kota Ambon)

JAKARTA - Banjir yang melanda wilayah Kota Ambon, Provinsi Maluku pada Selasa (26/7) kini mulai berangsur surut. Kondisi curah hujan tinggi dan jebolnya tanggul bandara memicu banjir yang masuk hingga ke pemukiman warga. Hal ini juga mengakibatkan longsor di beberapa titik.
BPBD Kota Ambon mencatat sebanyak enam unit rumah terdampak dan lima unit berpotensi longsor. Selain itu, terdapat 6 KK/24 jiwa terdampak di Desa Laha Kecamatan Teluk ambon dan Desa Hattu di Kecamatan Leihitu Barat.
Banjir tersebut sempat membuat aktivitas para warga tersendat. Berdasarkan pantauan visual dilapangan, tinggi muka air sebelumnya terpantu hingga 1,5 meter. Para warga menggunakan tali untuk membantu berjalan kaki.
Pusat Pengendalian Operasi (Pusdalops) BNPB melaporkan berdasarkan informasi per Selasa (26/7) pukul 17.00 WIT kini akses jalan sudah bisa dilalui kendaraan truk. Upaya penanganan darurat juga terus dilakukan BPBD Kota Ambon dengan menjalin koordinasi antar lintas unit terkait pendataan dan distribusi permakanan bagi para warga terdampak.
Merujuk informasi peringatan dini dari BMKG esok hari (28/7) untuk wilayah Ambon masih berpotensi hujan dengan intensitas ringan hingga sedang disertai petir. Menindaklanjuti informasi ini, BNPB mengimbau masyarakat dan perangkat daerah setempat untuk meningkatkan kewaspadaan dan kesiapsiagaan terhadap potensi bencana hidrometeorologi.
Masyarakat dan perangkat daerah setempat dapat melakukan langkah-langkah kesiapsiagaan dengan membersihkan area aliran sungai dari beragam material yang menghambat aliran air, memantau peningkatan debit air ketika hujan berdurasi lama serta mengikuti instruksi otoritas daerah setempat dalam upaya tanggap darurat banjir.

Abdul Muhari, Ph.D.
Plt. Kepala Pusat Data, Informasi dan Komunikasi Kebencanaan BNPB
  Nabilla/Shakira/Anggita/Apri
  Apri Setiawan
Banjir Kecamatan Bintan Timur Berangsur Surut
Pemkab Lanny Jaya Aktifkan Posko Tangani Bencana Kekeringan
Telp.021-29827793
Fax.021-21281200
Email: [email protected]
Telp. +62 21 29827444 , 117
+62 812 1237 575
Email:[email protected]

In [100]:
df["newcontent"].str.lower()

0    jakarta - banjir yang melanda wilayah kota amb...
Name: newcontent, dtype: str

In [97]:
import re
def elimination(text):
     # Remove date/view count lines (start with digit + month + year)
    text = re.sub(r'^\s*\d{1,2}\s\w+\s\d{4}.*$', '', text, flags=re.MULTILINE)
    
    # Remove "Dilihat ... kali" lines
    text = re.sub(r'^\s*Dilihat.*$', '', text, flags=re.MULTILINE)
    
    # Remove photo captions (lines containing "Foto :")
    text = re.sub(r'^\s*Foto\s*:.*$', '', text, flags=re.MULTILINE)
    
    # Remove footer lines (Telp, Fax, Email, phone numbers, names)
    text = re.sub(r'^\s*(Telp.*|Fax.*|Email.*|\+?\d[\d\s]+)$', '', text, flags=re.MULTILINE)
    
    # Collapse multiple blank lines
    text = re.sub(r'\n+', '\n', text)
    return text.strip()

In [98]:
df["newcontent"] = df["content"].apply(elimination)

In [99]:
print(df["newcontent"][0])

JAKARTA - Banjir yang melanda wilayah Kota Ambon, Provinsi Maluku pada Selasa (26/7) kini mulai berangsur surut. Kondisi curah hujan tinggi dan jebolnya tanggul bandara memicu banjir yang masuk hingga ke pemukiman warga. Hal ini juga mengakibatkan longsor di beberapa titik.
BPBD Kota Ambon mencatat sebanyak enam unit rumah terdampak dan lima unit berpotensi longsor. Selain itu, terdapat 6 KK/24 jiwa terdampak di Desa Laha Kecamatan Teluk ambon dan Desa Hattu di Kecamatan Leihitu Barat.
Banjir tersebut sempat membuat aktivitas para warga tersendat. Berdasarkan pantauan visual dilapangan, tinggi muka air sebelumnya terpantu hingga 1,5 meter. Para warga menggunakan tali untuk membantu berjalan kaki.
Pusat Pengendalian Operasi (Pusdalops) BNPB melaporkan berdasarkan informasi per Selasa (26/7) pukul 17.00 WIT kini akses jalan sudah bisa dilalui kendaraan truk. Upaya penanganan darurat juga terus dilakukan BPBD Kota Ambon dengan menjalin koordinasi antar lintas unit terkait pendataan dan distribusi permakanan bagi para warga terdampak.
Merujuk informasi peringatan dini dari BMKG esok hari (28/7) untuk wilayah Ambon masih berpotensi hujan dengan intensitas ringan hingga sedang disertai petir. Menindaklanjuti informasi ini, BNPB mengimbau masyarakat dan perangkat daerah setempat untuk meningkatkan kewaspadaan dan kesiapsiagaan terhadap potensi bencana hidrometeorologi.
Masyarakat dan perangkat daerah setempat dapat melakukan langkah-langkah kesiapsiagaan dengan membersihkan area aliran sungai dari beragam material yang menghambat aliran air, memantau peningkatan debit air ketika hujan berdurasi lama serta mengikuti instruksi otoritas daerah setempat dalam upaya tanggap darurat banjir.
Abdul Muhari, Ph.D.
Plt. Kepala Pusat Data, Informasi dan Komunikasi Kebencanaan BNPB
  Nabilla/Shakira/Anggita/Apri
  Apri Setiawan
Banjir Kecamatan Bintan Timur Berangsur Surut
Pemkab Lanny Jaya Aktifkan Posko Tangani Bencana Kekeringan

In [101]:
import re

paragraphs = df["newcontent"][0]

# Split into sentences
sentences = re.split(r'\.\s*', paragraphs)

# Clean up and add back the period
sentences = [s.strip() + '.' for s in sentences if s.strip()]

# Now sentences is already a list
print(sentences)

['JAKARTA - Banjir yang melanda wilayah Kota Ambon, Provinsi Maluku pada Selasa (26/7) kini mulai berangsur surut.', 'Kondisi curah hujan tinggi dan jebolnya tanggul bandara memicu banjir yang masuk hingga ke pemukiman warga.', 'Hal ini juga mengakibatkan longsor di beberapa titik.', 'BPBD Kota Ambon mencatat sebanyak enam unit rumah terdampak dan lima unit berpotensi longsor.', 'Selain itu, terdapat 6 KK/24 jiwa terdampak di Desa Laha Kecamatan Teluk ambon dan Desa Hattu di Kecamatan Leihitu Barat.', 'Banjir tersebut sempat membuat aktivitas para warga tersendat.', 'Berdasarkan pantauan visual dilapangan, tinggi muka air sebelumnya terpantu hingga 1,5 meter.', 'Para warga menggunakan tali untuk membantu berjalan kaki.', 'Pusat Pengendalian Operasi (Pusdalops) BNPB melaporkan berdasarkan informasi per Selasa (26/7) pukul 17.', '00 WIT kini akses jalan sudah bisa dilalui kendaraan truk.', 'Upaya penanganan darurat juga terus dilakukan BPBD Kota Ambon dengan menjalin koordinasi antar lintas unit terkait pendataan dan distribusi permakanan bagi para warga terdampak.', 'Merujuk informasi peringatan dini dari BMKG esok hari (28/7) untuk wilayah Ambon masih berpotensi hujan dengan intensitas ringan hingga sedang disertai petir.', 'Menindaklanjuti informasi ini, BNPB mengimbau masyarakat dan perangkat daerah setempat untuk meningkatkan kewaspadaan dan kesiapsiagaan terhadap potensi bencana hidrometeorologi.', 'Masyarakat dan perangkat daerah setempat dapat melakukan langkah-langkah kesiapsiagaan dengan membersihkan area aliran sungai dari beragam material yang menghambat aliran air, memantau peningkatan debit air ketika hujan berdurasi lama serta mengikuti instruksi otoritas daerah setempat dalam upaya tanggap darurat banjir.', 'Abdul Muhari, Ph.', 'D.', 'Plt.', 'Kepala Pusat Data, Informasi dan Komunikasi Kebencanaan BNPB\n  Nabilla/Shakira/Anggita/Apri \n  Apri Setiawan \nBanjir Kecamatan Bintan Timur Berangsur Surut\nPemkab Lanny Jaya Aktifkan Posko Tangani Bencana Kekeringan.']

In [104]:
vectorizer = CountVectorizer(vocabulary=['banjir', 'warga'])
x = vectorizer.fit_transform(sentences)
print(x.toarray())

[[1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]]

In [105]:
#Count the Cosine Similarity 
con_sim = cosine_similarity(x[0:1],x)

#showing the result
df = pd.DataFrame(x.toarray(), columns=['banjir','warga'])
df['Cosine Sim to Doc 0'] = con_sim.flatten()
print(df)

    banjir  warga  Cosine Sim to Doc 0
0        1      0             1.000000
1        1      1             0.707107
2        0      0             0.000000
3        0      0             0.000000
4        0      0             0.000000
5        1      1             0.707107
6        0      0             0.000000
7        0      1             0.000000
8        0      0             0.000000
9        0      0             0.000000
10       0      1             0.000000
11       0      0             0.000000
12       0      0             0.000000
13       1      0             1.000000
14       0      0             0.000000
15       0      0             0.000000
16       0      0             0.000000
17       1      0             1.000000

In [109]:
from collections import Counter 
tf = pd.DataFrame(
    [Counter(doc.split()) for doc in sentences],).fillna(0)
tf

,JAKARTA,-,Banjir,yang,melanda,wilayah,Kota,"Ambon,",Provinsi,Maluku,...,Berangsur,Surut,Pemkab,Lanny,Jaya,Aktifkan,Posko,Tangani,Bencana,Kekeringan.
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [111]:
import numpy as np
def length(v):
    return np.sqrt((v ** 2).sum())
def cos_dist(v, w):
    return 1 - (v * w).sum() / (length(v) * length(w))
cos_dist(tf.loc[0], tf.loc[1]), cos_dist(tf.loc[0], tf.loc[2])

(np.float64(0.9393660937409167), np.float64(1.0))

In [115]:
full_cos_sim_matrix = cosine_similarity(x)

# Display the full matrix as a DataFrame for better readability
cos_sim_df = pd.DataFrame(full_cos_sim_matrix, index=[f'Doc {i}' for i in range(len(sentences))], columns=[f'Doc {i}' for i in range(len(sentences))])
print("Full Cosine Similarity Matrix:")
print(cos_sim_df)

Full Cosine Similarity Matrix:
           Doc 0     Doc 1  Doc 2  Doc 3  Doc 4     Doc 5  Doc 6     Doc 7  \
Doc 0   1.000000  0.707107    0.0    0.0    0.0  0.707107    0.0  0.000000
Doc 1   0.707107  1.000000    0.0    0.0    0.0  1.000000    0.0  0.707107
Doc 2   0.000000  0.000000    0.0    0.0    0.0  0.000000    0.0  0.000000
Doc 3   0.000000  0.000000    0.0    0.0    0.0  0.000000    0.0  0.000000
Doc 4   0.000000  0.000000    0.0    0.0    0.0  0.000000    0.0  0.000000
Doc 5   0.707107  1.000000    0.0    0.0    0.0  1.000000    0.0  0.707107
Doc 6   0.000000  0.000000    0.0    0.0    0.0  0.000000    0.0  0.000000
Doc 7   0.000000  0.707107    0.0    0.0    0.0  0.707107    0.0  1.000000
Doc 8   0.000000  0.000000    0.0    0.0    0.0  0.000000    0.0  0.000000
Doc 9   0.000000  0.000000    0.0    0.0    0.0  0.000000    0.0  0.000000
Doc 10  0.000000  0.707107    0.0    0.0    0.0  0.707107    0.0  1.000000
Doc 11  0.000000  0.000000    0.0    0.0    0.0  0.000000    0.0  0.000000
Doc 12  0.000000  0.000000    0.0    0.0    0.0  0.000000    0.0  0.000000
Doc 13  1.000000  0.707107    0.0    0.0    0.0  0.707107    0.0  0.000000
Doc 14  0.000000  0.000000    0.0    0.0    0.0  0.000000    0.0  0.000000
Doc 15  0.000000  0.000000    0.0    0.0    0.0  0.000000    0.0  0.000000
Doc 16  0.000000  0.000000    0.0    0.0    0.0  0.000000    0.0  0.000000
Doc 17  1.000000  0.707107    0.0    0.0    0.0  0.707107    0.0  0.000000

        Doc 8  Doc 9    Doc 10  Doc 11  Doc 12    Doc 13  Doc 14  Doc 15  \
Doc 0     0.0    0.0  0.000000     0.0     0.0  1.000000     0.0     0.0
Doc 1     0.0    0.0  0.707107     0.0     0.0  0.707107     0.0     0.0
Doc 2     0.0    0.0  0.000000     0.0     0.0  0.000000     0.0     0.0
Doc 3     0.0    0.0  0.000000     0.0     0.0  0.000000     0.0     0.0
Doc 4     0.0    0.0  0.000000     0.0     0.0  0.000000     0.0     0.0
Doc 5     0.0    0.0  0.707107     0.0     0.0  0.707107     0.0     0.0
Doc 6     0.0    0.0  0.000000     0.0     0.0  0.000000     0.0     0.0
Doc 7     0.0    0.0  1.000000     0.0     0.0  0.000000     0.0     0.0
Doc 8     0.0    0.0  0.000000     0.0     0.0  0.000000     0.0     0.0
Doc 9     0.0    0.0  0.000000     0.0     0.0  0.000000     0.0     0.0
Doc 10    0.0    0.0  1.000000     0.0     0.0  0.000000     0.0     0.0
Doc 11    0.0    0.0  0.000000     0.0     0.0  0.000000     0.0     0.0
Doc 12    0.0    0.0  0.000000     0.0     0.0  0.000000     0.0     0.0
Doc 13    0.0    0.0  0.000000     0.0     0.0  1.000000     0.0     0.0
Doc 14    0.0    0.0  0.000000     0.0     0.0  0.000000     0.0     0.0
Doc 15    0.0    0.0  0.000000     0.0     0.0  0.000000     0.0     0.0
Doc 16    0.0    0.0  0.000000     0.0     0.0  0.000000     0.0     0.0
Doc 17    0.0    0.0  0.000000     0.0     0.0  1.000000     0.0     0.0

        Doc 16    Doc 17
Doc 0      0.0  1.000000
Doc 1      0.0  0.707107
Doc 2      0.0  0.000000
Doc 3      0.0  0.000000
Doc 4      0.0  0.000000
Doc 5      0.0  0.707107
Doc 6      0.0  0.000000
Doc 7      0.0  0.000000
Doc 8      0.0  0.000000
Doc 9      0.0  0.000000
Doc 10     0.0  0.000000
Doc 11     0.0  0.000000
Doc 12     0.0  0.000000
Doc 13     0.0  1.000000
Doc 14     0.0  0.000000
Doc 15     0.0  0.000000
Doc 16     0.0  0.000000
Doc 17     0.0  1.000000